### ISSUE TITLE
Wrong return type by SeriesGroupBy methods when as_index=False

### ISSUE THREAD

**Issue by wadhah101** [pandas-dev/pandas-stubs#553] opened 2023-02-22 18:08 UTC
**Describe the bug**
SeriesGroupBy methods are returning a Series when `as_index=False`. They should return a DataFrame 

**To Reproduce**
```python
import pandas as pd
df_example = pd.DataFrame({'a': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 'b': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]})
as_index_false: pd.DataFrame = df_example.groupby(['a'] , as_index=False)["a"].sum() # Incompatible types in assignment (expression has type "Series[Any]", variable has type "DataFrame")  [assignment]
print(type(as_index_false))
print(as_index_false)

# output
# <class 'pandas.core.frame.DataFrame'>
#     a
# 0   1
# 1   2
# 2   3
# 3   4
# 4   5
# 5   6
# 6   7
# 7   8
# 8   9
# 9  10
```

**Please complete the following information:**
 - OS: MacOS
 - OS 13.1
 - python : 3.10.9
 - mypy==1.0.1 
 - version of installed `pandas-stubs` :  pandas-stubs==1.5.3.230214

**Comment by Dr-Irv** [comment] 2023-02-22 20:03
Duplicate of #203

**Closed by Dr-Irv** 2023-02-22 20:03 UTC
