### ISSUE TITLE
`AggFuncTypeFrame` is partially Unknown

### ISSUE THREAD

**Issue by Avasam** [pandas-dev/pandas-stubs#811] opened 2023-11-03 23:40 UTC
**Describe the bug**

**To Reproduce**
1. Provide a minimal runnable `pandas` example that is not properly checked by the stubs.
2. Indicate which type checker you are using (`mypy` or  `pyright`).
3. Show the error message received from that type checker while checking your example.

`pyright` in `strict` mode:
```py
from pandas._typing import AggFuncTypeFrame

def foo(bar: AggFuncTypeFrame): ...
```

```py
error: Type of "AggFuncTypeFrame" is partially unknown
    Type of "AggFuncTypeFrame" is "type[(...) -> Unknown] | type[str] | type[ufunc] | type[list[((...) -> Unknown) | str | ufunc]] | type[Mapping[Unknown, ((...) -> Unknown) | str | ufunc | list[((...) -> Unknown) | str | ufunc]]]" (reportUnknownVariableType)
error: Type of parameter "bar" is partially unknown
    Parameter type is "((...) -> Unknown) | str | ufunc | list[((...) -> Unknown) | str | ufunc] | Mapping[Unknown, ((...) -> Unknown) | str | ufunc | list[((...) -> Unknown) | str | ufunc]]" (reportUnknownParameterType)
```

This is due to the partial `Callable`, which could instead be `Callable[..., Any]` or `Callable[..., object]` (sorry I always get confused about variance, can't remember if `object` is fine here).
As well as missing a type argument to `AggFuncTypeDictFrame` in `AggFuncTypeFrame`'s alias.

**Please complete the following information:**
 - OS: Windows
 - OS Version	10.0.19045 Build 19045
 - python version: 3.9.13
 - version of type checker: pyright@1.1.334
 - version of installed `pandas-stubs`: 2.1.1.230928

**Additional context**
Noticed while drilling down seaborn types to complete some method signatures in typeshed

**Comment by Dr-Irv** [comment] 2023-11-06 14:16
We don't support the `strict` setting of `pyright`.  In this particular case, the issue is that we have to support any type of `Callable`, which is "partially unknown"

So we won't provide a fix for this.

**Closed by Dr-Irv** 2023-11-06 14:16 UTC
