### ISSUE TITLE
groupby with MultiIndex not annotated correctly

### ISSUE THREAD

**Issue by behrenhoff** [pandas-dev/pandas-stubs#703] opened 2023-05-22 13:55 UTC
Consider a DF or Series with a MultiIndex M1, M2, M3.

When grouping as in
`grp = df.groupby(level=["M1", "M3"])`

You will get an error like 
```
Argument of type "list[str]" cannot be assigned to parameter "level" of type "Level | None" in function "groupby"
  Type "list[str]" cannot be assigned to type "Level | None"
    "list[str]" is incompatible with protocol "Hashable"
```

This is due to the annotation of groupby as
```
        by: IntervalIndex[IntervalT],
        axis: AxisIndex = ...,
        level: Level | None = ...,
```
The type "Level" is an alias for "Hashable" and allows only one level. I think it should be `Hashable|Sequence[Hashable]` or, as pandas calls it, `IndexLabel` (+ the `| None`)

I've identified a few places (see attachment). However, I am not sure the patch is correct/complete. It is interesting to see that `stack` is annotated with `level: Level | list[Level] = ...` while `unstack` has `level: Level = ...` while IMHO both should be `IndexLabel`.

Also, I am not sure the groupby annotations are completey correct because I think you cannot use `df.groupby(by=not_None, level=other_not_None)` at the same time, yet the annotations seems to allow it.

Minimum example code:
```
import pandas as pd

df = pd.DataFrame(
    data={"a": [0]},
    index=pd.MultiIndex.from_product(
        [pd.Index(["i1a"], name="i1"), pd.Index(["i2a"], name="i2")]
    ),
)
grp = df.groupby(level=["i1", "i2"])
```
pyright outputs:
```
pyright pd-stub-test.py
pd-stub-test.py
  pd-stub-test.py:9:24 - error: Argument of type "list[str]" cannot be assigned to parameter "level" of type "Level | None" in function "groupby"
    Type "list[str]" cannot be assigned to type "Level | None"
      "list[str]" is incompatible with protocol "Hashable"
        "__hash__" is an incompatible type
          Type "None" cannot be assigned to type "(self: list[str]) -> int"
      "list[str]" is incompatible with "int"
      Type cannot be assigned to type "None" (reportGeneralTypeIssues)
1 error, 0 warnings, 0 informations 
```

[0001-MultiIndex-in-groupby.patch.gz](https://github.com/pandas-dev/pandas-stubs/files/11531746/0001-MultiIndex-in-groupby.patch.gz)

(Warning: I haven't tested/verified the patch!)

**Comment by Dr-Irv** [comment] 2023-05-22 14:09
Can you indicate which version of pandas-stubs you are using?

**Comment by behrenhoff** [comment] 2023-05-22 14:15
I am using `pandas-stubs==1.5.3.230321` but you can find the issue in the main branch (pulled appox 1h ago) as well. The attached patch is against the current main.
See for example https://github.com/pandas-dev/pandas-stubs/blob/main/pandas-stubs/core/frame.pyi line 1077.

**Comment by behrenhoff** [comment] 2023-05-22 14:29
You absolutely can! Also, I suspect we can find more of these things.

**Comment by janrito** [comment] 2023-09-06 19:59
This happens with a Series as well:

```python
grp = series.groupby(level=["l1", "l2"])
```

due to this https://github.com/pandas-dev/pandas-stubs/blob/6bb12157a810cc26e034e012bff6a0ec2da191d0/pandas-stubs/core/series.pyi#L609

**Comment by loicdiridollou** [comment] 2024-09-23 23:52
This seems to have been fixed (or I can't reproduce it anymore on the latest version).
Now the typing is `IndexLabel | None = ...` so this could probably be closed @Dr-Irv. Let me know if I missed something.

**Comment by Dr-Irv** [comment] 2024-09-24 21:39
Yes, seems like #837 closed this.

**Closed by Dr-Irv** 2024-09-24 21:39 UTC
