### ISSUE TITLE
Annotation of `get_loc` does no longer fit to `iloc` resulting in many false positive type errors.

### ISSUE THREAD

**Issue by bluenote10** [pandas-dev/pandas-stubs#938] opened 2024-06-10 15:07 UTC
**Describe the bug**

The signature of `DataFrame.columns.get_loc` is no longer compatible with `df.iloc`. In our code base, this is resulting in a significant amount of false positive type errors.

**To Reproduce**

```py
import pandas as pd

df = pd.DataFrame({"foo": [1, 2, 3], "bar": [4, 5, 6]})
df.iloc[1:, df.columns.get_loc("bar")] += 10

print(df)
```
This should be standard/valid Pandas, and works at runtime, producing:
```
   foo  bar
0    1    4
1    2   15
2    3   16
```

Given the current stubs, it doesn't type check with either `pyright` or `mypy`. The error in mypy is:

```
_debug_pandas_stubs.py:4: error: No overload variant of "__add__" of "Timestamp" matches argument type "int"  [operator]
_debug_pandas_stubs.py:4: note: Possible overload variants:
_debug_pandas_stubs.py:4: note:     def __add__(self, ndarray[Any, dtype[timedelta64]], /) -> ndarray[Any, dtype[datetime64]]
_debug_pandas_stubs.py:4: note:     def __add__(self, timedelta | timedelta64 | Tick, /) -> Timestamp
_debug_pandas_stubs.py:4: note:     def __add__(self, TimedeltaSeries, /) -> TimestampSeries
_debug_pandas_stubs.py:4: note:     def __add__(self, TimedeltaIndex, /) -> DatetimeIndex
_debug_pandas_stubs.py:4: error: No overload variant of "__add__" of "Timedelta" matches argument type "int"  [operator]
_debug_pandas_stubs.py:4: note:     def __add__(self, timedelta | Timedelta | timedelta64, /) -> Timedelta
_debug_pandas_stubs.py:4: note:     def __add__(self, datetime | datetime64 | Timestamp, /) -> Timestamp
_debug_pandas_stubs.py:4: note:     def __add__(self, NaTType, /) -> NaTType
_debug_pandas_stubs.py:4: note:     def __add__(self, Period, /) -> Period
_debug_pandas_stubs.py:4: note:     def __add__(self, date, /) -> date
_debug_pandas_stubs.py:4: note:     def __add__(self, PeriodIndex, /) -> PeriodIndex
_debug_pandas_stubs.py:4: note:     def __add__(self, DatetimeIndex, /) -> DatetimeIndex
_debug_pandas_stubs.py:4: note:     def __add__(self, ndarray[Any, dtype[timedelta64]], /) -> ndarray[Any, dtype[timedelta64]]
_debug_pandas_stubs.py:4: note:     def __add__(self, ndarray[Any, dtype[datetime64]], /) -> ndarray[Any, dtype[datetime64]]
_debug_pandas_stubs.py:4: note:     def __add__(self, TimedeltaIndex, /) -> TimedeltaIndex
_debug_pandas_stubs.py:4: note:     def __add__(self, TimedeltaSeries, /) -> TimedeltaSeries
_debug_pandas_stubs.py:4: note:     def __add__(self, TimestampSeries, /) -> TimestampSeries
_debug_pandas_stubs.py:4: note: Left operand is of type "str | bytes | date | datetime | timedelta | datetime64 | timedelta64 | bool | int | float | Timestamp | Timedelta | complex"
_debug_pandas_stubs.py:4: error: Invalid index type "tuple[slice, int | slice | ndarray[Any, dtype[bool_]]]" for "_iLocIndexerFrame"; expected type "tuple[int, int]"  [index]
_debug_pandas_stubs.py:4: error: Invalid index type "tuple[slice, int | slice | ndarray[Any, dtype[bool_]]]" for "_iLocIndexerFrame"; expected type "int | slice | ndarray[Any, dtype[integer[Any]]] | Index[Any] | list[int] | Series[int] | tuple[int, int] | tuple[slice | ndarray[Any, dtype[integer[Any]]] | Index[Any] | list[int] | Series[int], int] | tuple[slice | ndarray[Any, dtype[integer[Any]]] | Index[Any] | list[int] | Series[int], slice | ndarray[Any, dtype[integer[Any]]] | Index[Any] | list[int] | Series[int]] | tuple[int, slice | ndarray[Any, dtype[integer[Any]]] | Index[Any] | list[int] | Series[int]]"  [index]
_debug_pandas_stubs.py:4: error: Unsupported operand types for + ("str" and "int")  [operator]
_debug_pandas_stubs.py:4: error: Unsupported operand types for + ("bytes" and "int")  [operator]
_debug_pandas_stubs.py:4: error: Unsupported operand types for + ("date" and "int")  [operator]
_debug_pandas_stubs.py:4: error: Unsupported operand types for + ("datetime" and "int")  [operator]
_debug_pandas_stubs.py:4: error: Unsupported operand types for + ("timedelta" and "int")  [operator]
Found 9 errors in 1 file (checked 1 source file)
```

**Please complete the following information:**
 - OS: Ubuntu
 - OS Version: 22.04
 - python version: 3.10.12
 - version of type checker: 1.10.0
 - version of installed `pandas-stubs`: 2.2.2.240603

**Additional context**

The code used to type check up to `pandas-stubs` version 2.1.4.231227, but fails to type check starting with 2.2.0.240218.

**Comment by Dr-Irv** [comment] 2024-06-10 16:57
I'm not sure we can solve this with the stubs.

The issue here is that we don't know if `get_loc()` will return `int`, `slice` or a mask (boolean array), because the underlying index may have duplicate values, which could be adjacent (result will be a slice) or apart (result will be a boolean array).   Then for `iloc`, the result will be different based on whether you have one of those 3 types as the input to `iloc`.

Your best solution would be to cast the result of `iloc` to what you expect (one of those 3 types).

I'm going to close this because I don't think the issue is fixable using static typing.

**Closed by Dr-Irv** 2024-06-10 16:57 UTC

**Comment by bluenote10** [comment] 2024-06-10 19:38
Indeed, after taking a closer look I would come to the same conclusion -- the interface is unfortunately not very type-friendly here. Thanks for clarifying!
