### ISSUE TITLE
Type check fails when passing Callable to `.loc[]`

### ISSUE THREAD

**Issue by MichaelHarrison-CE** [pandas-dev/pandas-stubs#256] opened 2022-09-02 17:24 UTC
**Describe the bug**
Running mypy on the code snippet below gives the following error due to the lambda in the `.loc[]`:

>  error: No overload variant of "__getitem__" of "_LocIndexerFrame" matches argument type "Callable[[Any], Any]"

However, this is valid Pandas and the code runs successfully. 

While passing a callable is not necessary in this example, it is useful when used as part of a method chain -- e.g. when filtering intermediate results within the chain, without having to assign an intermediate variable.

**To Reproduce**
```python
import pandas as pd

df_data = pd.DataFrame({'col1': ['a', 'b', 'b', 'c', 'c', 'c'], 'col2': [1,2,2,3,3,3]})
df_filtered = df_data.loc[lambda df: df['col2'] % 2 == 0]
print(df_filtered)
```
Using mypy, I get the error mentioned above.

**Please complete the following information:**
 - OS: Windows 10
 - OS Version: 10.0.19044
 - python version: 3.8.10
 - version of type checker: mypy 0.971
 - version of installed `pandas-stubs`: 1.4.3.220829

**Additional context**
For info, my python environment is:

<details>
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
</head>

<div style='display:inline-block'>

<body link="#0563C1" vlink="#954F72">

Package | Version
-- | --
mypy | 0.971
mypy-extensions | 0.4.3
nodeenv | 1.7.0
numpy | 1.23.2
pandas | 1.5.0rc0
pandas-stubs | 1.4.3.220829
pip | 22.2.2
pyright | 1.1.269
python-dateutil | 2.8.2
pytz | 2022.2.1
setuptools | 63.4.3
six | 1.16.0
tomli | 2.0.1
types-pytz | 2022.2.1.0
typing_extensions | 4.3.0
wheel | 0.37.1

</body>

</html>

</details>

And the  output from `pd.show_versions()` is:

<details>

INSTALLED VERSIONS
------------------
commit           : 224458ee25d92ccdf289d1ae2741d178df4f323e
python           : 3.8.10.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19044
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United Kingdom.1252

pandas           : 1.5.0rc0
numpy            : 1.23.2
pytz             : 2022.2.1
dateutil         : 2.8.2
setuptools       : 63.4.3
pip              : 22.2.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None

</details>

This  issue is a cross-post of https://github.com/pandas-dev/pandas/issues/48367

**Comment by Dr-Irv** [comment] 2022-09-02 18:03
The issue here is that any type checker cannot infer the type of the lambda function.  You have two options:

```python
    df_data = pd.DataFrame({'col1': ['a', 'b', 'b', 'c', 'c', 'c'], 'col2': [1,2,2,3,3,3]})
    def filter(df: pd.DataFrame):
        return df['col2'] % 2 == 0
    df_filtered = df_data.loc[filter(df)]
```
OR
```python
    df_data = pd.DataFrame({'col1': ['a', 'b', 'b', 'c', 'c', 'c'], 'col2': [1,2,2,3,3,3]})
    lf: Callable[[pd.DataFrame], pd.Series] = lambda df: df["col2"] % 2 == 0
    
    df_filtered = df_data.loc[lf(df)]
```

The inferred type of the `lambda` function as an argument is `Callable[[Any], Any]`, which is too wide from a pandas type checking perspective.

**Comment by maxbane** [comment] 2022-11-17 14:22
Hey @Dr-Irv, I think this merits another look. Your example workarounds are not quite right: you are passing the *result of applying* `filter`/`lf` (to undefined arguments, no less!), rather than passing the functions themselves to `loc[]`.

Below is an example where types should check out (the function argument to `loc[]` has type `Callable[[DataFrame], Series]` which should not be too broad, if I understand it), but mypy still freaks out.

As far as I can tell, it is currently impossible to provide *any* Callable argument to `DataFrame.loc[]` that satisfies `pandas-stubs`, so I think it is very likely an oversight. Any thoughts? The first overload variant reported by mypy looks suspect... why is the `Callable[..., Any]` nested inside a `Tuple`?

```python
import pandas as pd


def my_selector(df: pd.DataFrame) -> pd.Series:
    return df["price"] > 2.0


result = pd.DataFrame({
    "price": [1.0, 2.0, 3.0]
}).loc[my_selector]

print(result)
```

Mypy gives:
```
scratch_df_mypy.py:9: error: No overload variant of "__getitem__" of "_LocIndexerFrame" matches argument type "Callable[[DataFrame], Series[Any]]"  [call-overload]
scratch_df_mypy.py:9: note: Possible overload variants:
scratch_df_mypy.py:9: note:     def [HashableT <: Hashable] __getitem__(self, Union[slice, ndarray[Any, dtype[signedinteger[_64Bit]]], Index, List[int], Series[int], Series[bool], ndarray[Any, dtype[bool_]], List[bool], List[HashableT], Tuple[Union[slice, Index, List[int], Series[int], Series[bool], List[bool], List[HashableT], Hashable], Union[List[HashableT], slice, Series[bool], Callable[..., Any]]]], /) -> DataFrame
scratch_df_mypy.py:9: note:     def [ScalarT] __getitem__(self, Tuple[Union[int, str, Tuple[ScalarT, ...]], Union[int, str]], /) -> Union[str, bytes, date, datetime, timedelta, bool, int, float, complex, Timestamp, Timedelta]
scratch_df_mypy.py:9: note:     def [ScalarT] __getitem__(self, Union[ScalarT, Tuple[Union[slice, ndarray[Any, dtype[signedinteger[_64Bit]]], Index, List[int], Series[int], Series[bool], ndarray[Any, dtype[bool_]], List[bool], Tuple[Union[Index, Union[Series[bool], ndarray[Any, dtype[bool_]], List[bool]], Union[str, bytes, date, datetime, timedelta, bool, int, float, complex, Timestamp, Timedelta], List[Any], slice], ...]], Optional[ScalarT]], None], /) -> Series[Any]
Found 1 error in 1 file (checked 1 source file)
```

```
% pip show pandas-stubs
Name: pandas-stubs
Version: 1.5.1.221024
[...]
```

**Comment by Dr-Irv** [comment] 2022-11-17 14:46
@maxbane You are correct.  I'll reopen the issue and we can use your example as a test case.

**Comment by ischurov** [comment] 2023-01-04 18:19
I understand that after this bug would be fixed, it would still fail on something like `df[lambda x: x['var'] > 2]`, as lambda is of type `Callable[[Any], Any]`. I see the point from theoretical perspective (we need the Callable to take Series and return something that can be substituted into `[]`, like Series of `bool`s, etc), but it makes me pretty much unhappy as a practitioner. Currently, filter-by-callable with lambdas is my preferred way to do filters in pandas, especially with method chaining pattern. In fact, I see no other method-chaining friendly ways to do it, except of `.query`, which I pretty much dislike. (If I need to construct a `str` that is essentially a code, I feel that something is deeply wrong and broken.) So, the only way to make type-checker happy here and continue to use filter-by-callable with lambda functions is to add `# type: ignore` every time.

I feel that most of pandas users who use filter-by-callable use them in the same way as I do: with lambda functions. So, effectively forbidding lambda functions with type-checker here simply makes type-checking useless in this case.

I understand that with type checking, we usually try to be “as strict as possible”, but probably in this case we can sacrifice rigour for the sake of practical usefulness, and simply allow `Callable[[Any], Any]` here?

**Comment by Dr-Irv** [comment] 2023-01-04 19:12
> I feel that most of pandas users who use filter-by-callable use them in the same way as I do: with lambda functions. So, effectively forbidding lambda functions with type-checker here simply makes type-checking useless in this case.
> 
> I understand that with type checking, we usually try to be “as strict as possible”, but probably in this case we can sacrifice rigour for the sake of practical usefulness, and simply allow `Callable[[Any], Any]` here?

There's two schools of thought on this:
1. To protect pandas users, force them to declare the types of `Callable` that are passed into a pandas method that accepts a `Callable` .  The whole point of static type checking is to protect people from making mistakes, so by being strict, we are helping users write correct code.
2. Allow a wide `Callable[[Any], Any]` as you suggest, which allows the use of untyped `lambda` functions (and any untyped function, for that matter), which means that the type checker won't find any errors if the parameters or return type of the `Callable` is incorrect.

We've chosen (1) for now, because if you are using static type checking, then the philosophy is that you should write code that is type safe.  Using `lambda` functions is not type safe.

If we chose (2), then someone could write incorrect code like the following and the type checker wouldn't catch it:
```python
df = pd.DataFrame({"x": [1,2,3]})
df.loc[lambda x: str(x)]
```

I'm open to being convinced for (2) by other contributors, such as @twoertwein , @bashtage and @gandhis1

**Comment by twoertwein** [comment] 2023-01-04 19:29
> I'm open to being convinced for (2) by other contributors

I didn't know that `loc` accepts a `Callable` so please disregard my opinion.

I would slightly prefer 1 because most linters discourage lambda functions anyways (use `def` to define your function). If you "need" to use a lambda function, you can wrap it inside a cast statement.

**Comment by ischurov** [comment] 2023-01-04 23:26
Let me elaborate a bit on why I believe that (2) is better in this particular case.

### Method chaining and filtering

There are two ways to represent a sequence of operations with dataframes: it is either a sequence of assignments / inplace mutations, or method chaining. The latter became rather popular recently, particularly under influence of dplyr / tidyverse ecosystem, where a similar approach with the pipe operator `%>%` is used. New specific methods that make method chaining easier were introduced (e.g. `.pipe`, `.assign`, etc).

The usual selection-by-condition pattern in pandas (like `df[df['var'] > 3]`) is not compatible with method chaining, as dataframe name `df` is mentioned explicitly inside the condition. For example, the following code:

```
(df.assign(new_var=df['var'] ** 2)
    [df['new_var'] > 10])
```
will fail.

There are two alternatives that are compatible with method chaining: method `.query` and selection-by-callable with lambda functions.

With `.query`, you have to provide a query as a string, that represents an expression that is parsed and executed, e.g. the fixed version of the aforementioned example looks like this:

```
(df.assign(new_var=df['var'] ** 2)
    .query('new_var > 10'))
```
Here instead of `new_var > 10` one may write more complex expressions that are processed and executed by pandas.

With selection-by-callable, you provide a lambda function instead of string:

```
(df.assign(new_var=df['var'] ** 2)
    [lambda x: x['new_var'] > 10]
```

### What happens if we forbid filter-by-callable with lambdas
I am not aware of any other ways to do filtering in pandas that is compatible with method chaining, other than the two mentioned above. Thus, if we forbid selection-by-callable with lambdas on grounds of type-safety, we push developers to use `.query` method instead. However, `.query` method is equally type-unsafe: as the expression that defines the condition is encoded into the string, no generic static type-checker can look inside it. Basically, it is even worse than untyped lambdas: with lambdas, at least syntax correctness can be checked statically. With `.query`, nothing can be said before the run time. And of course it is easy to bypass the type-checker, e.g. the following code will be marked as correct:

```
df = pd.DataFrame(dict(var=[1, 2, 3]))
class MySomething:
    pass
def foo(x):
    return MySomething()
df.query("@foo(var)") # equivalent of df[foo(df['var'])], i.e. df[MySomething()]
```

### Why not use named functions instead of lambdas?
The only type-correct way to use selection-by-callable provided that strict approach will be chosen is the following:

```
def is_var_greater_than_two(df: pd.DataFrame) -> pd.Series:
    return df['var'] > 2
df[is_var_greater_than_two]
```

It is not very convenient, to say the least. One need to declare the condition in advance, give it a name, specify the types of input and output, specify the condition, and only then use it. Unreadable and monstrous.

### We have to discourage lambdas anyway, they are type-unsafe

It is basically not possible to do method-chaining in pandas without lambdas. Besides filtering, another natural example is the `.assign` method that is usually combined with `lambdas` to create new columns. Moreover, pandas documentation uses lambdas in the [examples](https://pandas.pydata.org/docs/user_guide/indexing.html#indexing-callable) of filter-by-callable pattern. So, one may suggest that these features are specifically designed to be used with lambdas.

### Bottom line
If we forbid usage of lambdas in selection-by-callable pattern, we effectively forbid the usage of this pattern at all. Nobody will create a dedicated named and typed function just to express the condition like "variable > 20". It will not increase "type-safety" of the software, as the only alternative is `.query` method that is as unsafe as untyped lambdas, and even worse. Finally, we will declare a substantial part of pandas API that is specifically designed to be used in method-chaining to be effectively incompatible with any type-checking. I am very much in doubt that such decision would allow one to catch a single bug in a real-life situation: most probably it will lead just to turning of of the type-checking when working with this kind of pandas code. And turned off type-checker can find exactly 0 bugs.

**Comment by Dr-Irv** [comment] 2023-01-05 14:13
> The only type-correct way to use selection-by-callable provided that strict approach will be chosen is the following:
> 
> ```
> def is_var_greater_than_two(df: pd.DataFrame) -> pd.Series:
>     return df['var'] > 2
> df[is_var_greater_than_two]
> ```

You could also do the following using lambdas:
```python
df[cast(Callable[[pd.DataFrame], pd.Series], lambda df: df['var'] > 2)]
```
So that is a way of declaring the types of the `lambda` function, and making sure you're aware of the typing implications.

Maybe that is an acceptable compromise.  Yes, it requires modifying existing code, but it is more typesafe.

**Comment by ischurov** [comment] 2023-01-05 14:51
@Dr-Irv thanks, I wasn't aware of `cast`. However, the code becomes much less readable. Actually, the fact that we need to introduce lambda here already makes this kind of selection much more verbose than tidyverse's `df %>% filter(var > 2)`. Adding even more boilerplate code mostly to make type-checker happy doesn't look worthwhile to me: I doubt it will allow to catch any bugs inside the lambda, as these are usually short and pretty straightforward. And my bet is that developers would rather switch off the type-checker for the whole line with `# type: ignore` or switch to `.query`, which, as I said, even less type-safe.

Anyway, I want to stress that sticking with the strict approach here makes a well-known usage patterns, described in the official pandas documentation and adopted by the community, to be "incorrect" from the type-checker's point of view, without viable alternatives.

**Comment by Dr-Irv** [comment] 2023-01-05 15:31
> Anyway, I want to stress that sticking with the strict approach here makes a well-known usage patterns, described in the official pandas documentation and adopted by the community, to be "incorrect" from the type-checker's point of view, without viable alternatives.

I hear you, and that's why I want to hear from other contributors to get their opinion before making a decision.

You have to recognize that pandas was designed before python introduced type checking features.  My team at my company has used the pandas stubs on thousands of lines of code, and the stubs have helped us improve code quality.  The fundamental issue here is that a `lambda` function is  _dynamically_ typed, and type checkers are doing _static_ type checking.

In discussions I've seen in the typing community, it seems that the trend is to be more strict with type declarations, which might increase the verbosity of code, with the benefit of catching improper use of libraries.

Here's an example that illustrates the different result you can get based on what the lambda function is returning:
```python
>>> df = pd.DataFrame({"x": [1, 2, 3], "y": [4,5,6]})
>>> df
   x  y
0  1  4
1  2  5
2  3  6
>>> df.loc[lambda df: df["x"]==1, :]
   x  y
0  1  4
>>> df.loc[lambda df: [i for i in df.index if i % 2 == 1], "x"]
1    2
Name: x, dtype: int64
>>> df.loc[lambda df: 1, "x"]
2
```

- In the first case, `lambda df: df["x"]==1` would be typed as `Callable[[DataFrame], Series]`.
- In the second case, `lambda df: [i for i in df.index if i % 2 == 1]` would be typed as `Callable[[DataFrame], list]`
- In the third case, `lambda df: 1` would be typed as `Callable[[DataFrame], int]`

So we can't just put `Callable` in each of the overloads for `.loc[]`, because overloads would overlap, and you can't infer the type of the result without knowing the type of the `Callable`.

**Comment by ischurov** [comment] 2023-01-05 19:10
@Dr-Irv thanks, I understand the argument that the type of the selection result depends on the type of the selector. Though, it is unfortunate that we cannot infer the type of lambda automatically…

**Comment by Dr-Irv** [comment] 2023-01-05 19:28
> @Dr-Irv thanks, I understand the argument that the type of the selection result depends on the type of the selector. Though, it is unfortunate that we cannot infer the type of lambda automatically…

That's a limitation of python typing.  See https://peps.python.org/pep-3107/#lambda

**Closed** 2023-01-13 16:42 UTC
