### ISSUE TITLE
Remove <3.12 Requirement for Python

### ISSUE THREAD

**Issue by rbebb** [pandas-dev/pandas-stubs#642] opened 2023-04-11 15:16 UTC
**Describe the bug**
Since `pandas-stubs` has an upper Python version bound, all downstream projects that use [poetry](https://github.com/python-poetry/poetry) to manage dependencies have to set their upper Python version bound to <3.12. While this doesn't necessarily cause any issues, it would be great for downstream projects to be able to leave the version range open (i.e. >=3.8)

**To Reproduce**
1. Add `pandas-stubs` as a dependency to a poetry project
2. Run `poetry lock`
3. Check if the output says to set the upper Python version bound to <3.12

**Comment by gandhis1** [comment] 2023-04-11 15:27
Duplicate of https://github.com/pandas-dev/pandas-stubs/issues/625.

**Comment by Dr-Irv** [comment] 2023-04-11 16:19
Closing as it is dup of #625

**Closed by Dr-Irv** 2023-04-11 16:19 UTC
