### ISSUE TITLE
Argument of type `str` cannot be assigned to parameter `index_col` in function `read_excel`

### ISSUE THREAD

**Issue by takuminakaso** [pandas-dev/pandas-stubs#889] opened 2024-03-15 01:54 UTC
**Describe the bug**
Argument of type `str` can be assigned to parameter `index_col` in function `read_excel` as the document [pandas.read_excel — pandas 2.2.1 documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_excel.html), but `index_col` is defined to be type `int | Sequence[int] | None`.

**To Reproduce**
1. Provide a minimal runnable `pandas` example that is not properly checked by the stubs.

```python
import pandas as pd

df = pd.DataFrame([("a", "b"), ("c", "d")], index=pd.Series([1, 2], name="index"), columns=["col1", "col2"])
df.to_excel("/tmp/example.xlsx")
pd.read_excel("/tmp/example.xlsx", index_col="index")
```

2. Indicate which type checker you are using (`mypy` or  `pyright`).

pyright v1.1.352

3. Show the error message received from that type checker while checking your example.

```
:5:46 - error: Argument of type "Literal['index']" cannot be assigned to parameter "index_col" of type "int | Sequence[int] | None" in function "read_excel"
    Type "Literal['index']" cannot be assigned to type "int | Sequence[int] | None"
      "Literal['index']" is incompatible with "int"
      "Literal['index']" is incompatible with "Sequence[int]"
        Type parameter "_T_co@Sequence" is covariant, but "str" is not a subtype of "int"
          "str" is incompatible with "int"
      "Literal['index']" is incompatible with "None" (reportArgumentType)
```

**Please complete the following information:**
 - OS: Ubuntu
 - OS Version: 20.04 LTS
 - python version: v3.10.3
 - version of type checker: pyright v1.1.352
 - version of installed `pandas-stubs`: v2.2.0.240218

**Additional context**

**Comment by Dr-Irv** [comment] 2024-03-15 14:27
Duplicate of #809

**Closed by Dr-Irv** 2024-03-15 14:27 UTC
